import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.portfolio': 'Portfolio',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',

    // Hero Section
    'hero.title.we': 'We Create',
    'hero.title.digital': 'Digital',
    'hero.title.experiences': 'Experiences',
    'hero.subtitle': 'Transform your brand with cutting-edge digital solutions that captivate, convert, and accelerate business growth.',
    'hero.cta.start': 'Start Your Project',
    'hero.cta.view': 'View Our Work',

    // Portfolio Section
    'portfolio.title': 'Our',
    'portfolio.title.highlight': 'Portfolio',
    'portfolio.subtitle': 'Discover how we\'ve helped businesses transform their digital presence and achieve remarkable results.',
    'portfolio.cta.viewCase': 'View Case Study',
    'portfolio.cta.discuss': 'Discuss Your Project',
    'portfolio.modal.challenge': 'Challenge',
    'portfolio.modal.solution': 'Solution',
    'portfolio.modal.results': 'Results',
    'portfolio.modal.technologies': 'Technologies Used',
    'portfolio.modal.ready': 'Ready to achieve similar results?',
    'portfolio.modal.cta': 'Start Your Project',

    // Services Section
    'services.title': 'Our',
    'services.title.highlight': 'Services',
    'services.subtitle': 'Comprehensive digital solutions tailored to your business needs.',
    'services.strategy.title': 'Strategy & Consulting',
    'services.strategy.description': 'Strategic planning and consulting to align your digital initiatives with business goals.',
    'services.strategy.brand': 'Brand Strategy & Identity',
    'services.strategy.digital': 'Digital Transformation',
    'services.strategy.ux': 'UX/UI Strategy',
    'services.strategy.conversion': 'Conversion Optimization',
    'services.strategy.analytics': 'Analytics & Insights',
    'services.development.title': 'Development & Design',
    'services.development.description': 'Custom development and design solutions that bring your vision to life.',
    'services.development.web': 'Web Development',
    'services.development.mobile': 'Mobile App Development',
    'services.development.ecommerce': 'E-commerce Solutions',
    'services.development.custom': 'Custom Software',
    'services.development.api': 'API Development',
    'services.marketing.title': 'Digital Marketing',
    'services.marketing.description': 'Data-driven marketing strategies that drive growth and engagement.',
    'services.marketing.seo': 'SEO Optimization',
    'services.marketing.ppc': 'PPC Advertising',
    'services.marketing.social': 'Social Media Marketing',
    'services.marketing.content': 'Content Marketing',
    'services.marketing.email': 'Email Marketing',
    'services.cta.discuss': 'Discuss This Service',
    'services.cta.learn': 'Learn More',
    'services.cta.transform': 'Ready to transform your business?',
    'services.cta.getStarted': 'Get Started Today',

    // Testimonials Section
    'testimonials.title': 'What Our',
    'testimonials.title.highlight': 'Clients',
    'testimonials.title.say': 'Say',
    'testimonials.subtitle': "Don't just take our word for it. Here's what our clients say about working with us.",
    'testimonials.watchVideo': 'Watch Video',
    'testimonials.trustedAcross': 'Trusted Across Industries',
    'testimonials.quote1': 'Working with Premium Events Solution was a game-changer for our business. Their strategic approach and flawless execution delivered results beyond our expectations.',
    'testimonials.quote2': "The team's expertise in digital transformation helped us modernize our entire operation. Our efficiency has increased by 200%.",
    'testimonials.quote3': "Premium Events Solution doesn't just deliver projects, they deliver partnerships. Their ongoing support has been invaluable to our growth.",
    'testimonials.quote4': 'The Web app they developed has revolutionized how our customers interact with our services. User engagement is through the roof.',
    'testimonials.quote5': "Their healthcare platform solution has transformed our patient care delivery. We couldn't be happier with the results.",
    'testimonials.industry.technology': 'Technology',
    'testimonials.industry.saas': 'SaaS',
    'testimonials.industry.retail': 'Retail',
    'testimonials.industry.financial': 'Financial Services',
    'testimonials.industry.healthcare': 'Healthcare',
    'testimonials.project1': 'Digital Transformation',
    'testimonials.project2': 'SaaS Platform',
    'testimonials.project3': 'Brand Redesign',
    'testimonials.project4': 'Mobile App',
    'testimonials.project5': 'Healthcare Platform',
    'testimonials.metric.conversion': 'Conversion Rate',
    'testimonials.metric.revenue': 'Revenue Growth',
    'testimonials.metric.engagement': 'User Engagement',
    'testimonials.metric.acquisition': 'User Acquisition',
    'testimonials.metric.adoption': 'Feature Adoption',
    'testimonials.metric.market': 'Market Share',
    'testimonials.metric.recognition': 'Brand Recognition',
    'testimonials.metric.sales': 'Online Sales',
    'testimonials.metric.satisfaction': 'Customer Satisfaction',
    'testimonials.metric.downloads': 'App Downloads',
    'testimonials.metric.retention': 'User Retention',
    'testimonials.metric.transactions': 'Daily Transactions',
    'testimonials.metric.patientSat': 'Patient Satisfaction',
    'testimonials.metric.efficiency': 'Operational Efficiency',
    'testimonials.metric.platformAdoption': 'Platform Adoption',

    // About Section
    'about.title': 'About',
    'about.title.highlight': 'Premium Events Solution',
    'about.subtitle': 'We are a team of passionate digital innovators dedicated to transforming businesses through cutting-edge technology and creative excellence.',
    'about.stats.clients': 'Happy Clients',
    'about.stats.projects': 'Projects Completed',
    'about.stats.awards': 'Awards Won',
    'about.stats.experience': 'Years Experience',
    'about.mission.title': 'Our Mission',
    'about.mission.text': "To empower businesses with digital solutions that not only meet today's challenges but anticipate tomorrow's opportunities.",
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'The creative minds behind our success',
    'about.team.viewProfile': 'View Profile',
    'about.team.joined': 'Joined',
    'about.team.aboutPerson': 'About',
    'about.team.expertise': 'Expertise',
    'about.team.achievements': 'Key Achievements',
    'about.team.interests': 'Personal Interests',
    'about.team.workingStyle': 'Working Style',
    'about.culture.title': 'Our Culture & Values',
    'about.culture.innovation.title': 'Innovation First',
    'about.culture.innovation.description': 'We embrace cutting-edge technologies and creative solutions.',
    'about.culture.innovation.example1': 'Weekly innovation sessions',
    'about.culture.innovation.example2': 'Experimental project time',
    'about.culture.innovation.example3': 'Technology research initiatives',
    'about.culture.excellence.title': 'Excellence in Everything',
    'about.culture.excellence.description': 'We maintain the highest standards in all our work.',
    'about.culture.excellence.example1': 'Rigorous quality assurance',
    'about.culture.excellence.example2': 'Continuous improvement processes',
    'about.culture.excellence.example3': 'Industry best practices',
    'about.culture.partnership.title': 'True Partnership',
    'about.culture.partnership.description': 'We work as an extension of your team.',
    'about.culture.partnership.example1': 'Collaborative planning sessions',
    'about.culture.partnership.example2': 'Transparent communication',
    'about.culture.partnership.example3': 'Long-term relationship focus',
    'about.culture.balance.title': 'Work-Life Balance',
    'about.culture.balance.description': 'We believe great work comes from happy teams.',
    'about.culture.balance.example1': 'Flexible working arrangements',
    'about.culture.balance.example2': 'Wellness programs',
    'about.culture.balance.example3': 'Team building activities',
    'about.culture.inPractice': 'In Practice',
    'about.life.title': 'Life at Premium Events Solution',
    'about.life.subtitle': "More than just work - we're a community",
    'about.life.coffee.title': 'Coffee & Creativity',
    'about.life.coffee.description': 'Our best ideas happen over great coffee',
    'about.life.innovation.title': 'Innovation Labs',
    'about.life.innovation.description': 'Dedicated time for experimental projects',
    'about.life.balance.title': 'Work-Life Balance',
    'about.life.balance.description': 'Flexible schedules and remote work options',

    // Team member details
    'about.team.alex.role': 'Creative Director & Founder',
    'about.team.alex.bio': 'Visionary leader with 10+ years in digital design and strategy.',
    'about.team.alex.fullBio': 'Alex founded Premium Events Solution with a vision to bridge the gap between creative excellence and technical innovation. With over a decade of experience in digital design and strategy, Alex has led transformative projects for Fortune 500 companies and emerging startups alike.',
    'about.team.alex.expertise1': 'Creative Direction',
    'about.team.alex.expertise2': 'Brand Strategy',
    'about.team.alex.expertise3': 'Design Systems',
    'about.team.alex.expertise4': 'Team Leadership',
    'about.team.alex.achievement1': 'Led 50+ successful brand transformations',
    'about.team.alex.achievement2': 'Webby Award Winner 2023',
    'about.team.alex.achievement3': 'Featured in Design Week Magazine',
    'about.team.alex.achievement4': 'Speaker at 15+ industry conferences',
    'about.team.alex.interest1': 'Photography',
    'about.team.alex.interest2': 'Mountain Biking',
    'about.team.alex.interest3': 'Coffee Roasting',
    'about.team.alex.interest4': 'Travel',
    'about.team.alex.quote': 'Great design is not just about how it looks, but how it makes people feel.',
    'about.team.alex.workingStyle': 'Collaborative and hands-on, believes in leading by example and fostering creativity through open communication.',

    'about.team.sarah.role': 'Lead Developer',
    'about.team.sarah.bio': 'Full-stack developer passionate about creating scalable solutions.',
    'about.team.sarah.fullBio': "Sarah brings technical excellence and innovative problem-solving to every project. Her expertise spans modern web technologies and she's passionate about creating scalable, maintainable solutions that stand the test of time.",
    'about.team.sarah.expertise1': 'Full-Stack Development',
    'about.team.sarah.expertise2': 'Cloud Architecture',
    'about.team.sarah.expertise3': 'DevOps',
    'about.team.sarah.expertise4': 'Performance Optimization',
    'about.team.sarah.achievement1': 'Built 30+ scalable web applications',
    'about.team.sarah.achievement2': 'AWS Certified Solutions Architect',
    'about.team.sarah.achievement3': 'Open source contributor',
    'about.team.sarah.achievement4': 'Tech conference speaker',
    'about.team.sarah.interest1': 'Rock Climbing',
    'about.team.sarah.interest2': 'Cooking',
    'about.team.sarah.interest3': 'Board Games',
    'about.team.sarah.interest4': 'Podcasts',
    'about.team.sarah.quote': 'Code is poetry written for machines but read by humans.',
    'about.team.sarah.workingStyle': 'Detail-oriented and systematic, focuses on writing clean, maintainable code and mentoring junior developers.',

    'about.team.david.role': 'Digital Marketing Strategist',
    'about.team.david.bio': 'Data-driven marketer with expertise in growth hacking and analytics.',
    'about.team.david.fullBio': 'David combines analytical thinking with creative marketing strategies to drive measurable growth for our clients. His data-driven approach has helped numerous businesses achieve breakthrough results in their digital marketing efforts.',
    'about.team.david.expertise1': 'Growth Marketing',
    'about.team.david.expertise2': 'Analytics & Data',
    'about.team.david.expertise3': 'SEO/SEM',
    'about.team.david.expertise4': 'Conversion Optimization',
    'about.team.david.achievement1': 'Increased client ROI by 300% average',
    'about.team.david.achievement2': 'Google Ads certified expert',
    'about.team.david.achievement3': 'HubSpot certified trainer',
    'about.team.david.achievement4': 'Marketing automation specialist',
    'about.team.david.interest1': 'Data Science',
    'about.team.david.interest2': 'Basketball',
    'about.team.david.interest3': 'Reading',
    'about.team.david.interest4': 'Traveling',
    'about.team.david.quote': 'In marketing, data tells the story, but creativity brings it to life.',
    'about.team.david.workingStyle': 'Analytical and results-focused, believes in testing everything and making decisions based on solid data.',

    'about.team.maya.role': 'UX/UI Designer',
    'about.team.maya.bio': 'User-centered designer focused on creating intuitive digital experiences.',
    'about.team.maya.fullBio': 'Maya is passionate about creating digital experiences that are not only beautiful but also intuitive and accessible. Her user-centered design approach ensures that every interface we create truly serves the people who use it.',
    'about.team.maya.expertise1': 'User Experience Design',
    'about.team.maya.expertise2': 'Interface Design',
    'about.team.maya.expertise3': 'Design Systems',
    'about.team.maya.expertise4': 'User Research',
    'about.team.maya.achievement1': 'Designed 40+ award-winning interfaces',
    'about.team.maya.achievement2': 'UX certification from Nielsen Norman',
    'about.team.maya.achievement3': 'Accessibility advocate and trainer',
    'about.team.maya.achievement4': 'Design thinking workshop facilitator',
    'about.team.maya.interest1': 'Painting',
    'about.team.maya.interest2': 'Yoga',
    'about.team.maya.interest3': 'Sustainable Living',
    'about.team.maya.interest4': 'Museums',
    'about.team.maya.quote': 'Design is not just what it looks like and feels like. Design is how it works.',
    'about.team.maya.workingStyle': 'Empathetic and user-focused, conducts thorough research and iterates based on user feedback.',

    // Social Proof Section
    'socialProof.title': 'Trusted by',
    'socialProof.title.highlight': 'Industry Leaders',
    'socialProof.subtitle': 'Join the growing list of successful companies that trust us with their digital transformation.',
    'socialProof.industry.technology': 'Technology',
    'socialProof.industry.saas': 'SaaS',
    'socialProof.industry.retail': 'Retail',
    'socialProof.industry.fintech': 'FinTech',
    'socialProof.industry.healthcare': 'Healthcare',
    'socialProof.industry.education': 'Education',
    'socialProof.industry.energy': 'Energy',
    'socialProof.industry.food': 'Food & Beverage',
    'socialProof.awards.title': 'Awards & Recognition',
    'socialProof.awards.subtitle': 'Our work has been recognized by industry leaders',
    'socialProof.awards.webby.title': 'Webby Awards',
    'socialProof.awards.webby.category': 'Best Web Design',
    'socialProof.awards.webby.description': 'Recognized for outstanding web design and user experience',
    'socialProof.awards.css.title': 'CSS Design Awards',
    'socialProof.awards.css.category': 'Site of the Day',
    'socialProof.awards.css.description': 'Featured for innovative CSS design and creativity',
    'socialProof.awards.awwwards.title': 'Awwwards',
    'socialProof.awards.awwwards.category': 'Developer Award',
    'socialProof.awards.awwwards.description': 'Honored for technical excellence and innovation',
    'socialProof.awards.fwa.title': 'FWA',
    'socialProof.awards.fwa.category': 'Site of the Month',
    'socialProof.awards.fwa.description': 'Celebrated for cutting-edge web development',
    'socialProof.numbers.title': 'By the Numbers',
    'socialProof.numbers.subtitle': 'Our track record speaks for itself',
    'socialProof.stats.satisfaction.label': 'Client Satisfaction',
    'socialProof.stats.satisfaction.description': 'Average client satisfaction rating',
    'socialProof.stats.projects.label': 'Projects Completed',
    'socialProof.stats.projects.description': 'Successful projects delivered',
    'socialProof.stats.clients.label': 'Happy Clients',
    'socialProof.stats.clients.description': "Businesses we've helped grow", 
    'socialProof.stats.experience.label': 'Years Experience',
    'socialProof.stats.experience.description': 'Combined team experience',
    'socialProof.partners.title': 'Certifications & Partnerships',
    'socialProof.partners.subtitle': 'We maintain the highest industry standards',
    'socialProof.certifications.google': 'Google Partner',
    'socialProof.certifications.aws': 'AWS Certified',
    'socialProof.certifications.hubspot': 'HubSpot Partner',
    'socialProof.certifications.shopify': 'Shopify Expert',
    'socialProof.certifications.meta': 'Meta Partner',
    'socialProof.certifications.microsoft': 'Microsoft Partner',
    'socialProof.cta.text': 'Ready to join our success stories?',
    'socialProof.cta.button': 'Start Your Project',

    // Contact Section
    'contact.title': 'Let\'s',
    'contact.title.highlight': 'Connect',
    'contact.subtitle': 'Ready to transform your digital presence? Let\'s discuss your project and explore how we can help you achieve your goals.',
    'contact.getInTouch': 'Get in Touch',
    'contact.description': 'We\'d love to hear about your project and discuss how we can help bring your vision to life.',
    'contact.email.description': 'Send us an email anytime',
    'contact.phone.description': 'Call us during business hours',
    'contact.location.description': 'Visit our office',
    'contact.whatToExpected': 'What to Expect',
    'contact.form.title': 'Send us a message',
    'contact.form.subtitle': 'Fill out the form below and we\'ll get back to you within 24 hours.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message Sent!',
    'contact.form.successText': 'Thank you for your message. We\'ll get back to you within 24 hours.',
    'contact.form.privacy': 'We respect your privacy and will never share your information.',

    // Process steps
    'process.step1': 'Initial Response',
    'process.step1.desc': 'We\'ll respond within 24 hours',
    'process.step2': 'Discovery Call',
    'process.step2.desc': 'Free consultation to discuss your needs',
    'process.step3': 'Proposal',
    'process.step3.desc': 'Detailed proposal with timeline and pricing',

    // Validation messages
    'validation.nameRequired': 'Name is required',
    'validation.nameMinLength': 'Name must be at least 2 characters',
    'validation.emailRequired': 'Email is required',
    'validation.emailInvalid': 'Please enter a valid email address',
    'validation.messageRequired': 'Message is required',
    'validation.messageMinLength': 'Message must be at least 10 characters',
    'validation.messageMaxLength': 'Message must be less than 1000 characters',

    // Footer
    'footer.description': 'We create digital experiences that captivate, convert, and accelerate business growth.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.services.brand': 'Brand Strategy',
    'footer.services.web': 'Web Development',
    'footer.services.marketing': 'Digital Marketing',
    'footer.services.mobile': 'Mobile Apps',
    'footer.services.ecommerce': 'E-commerce',
    'footer.services.seo': 'SEO Optimization',
    'footer.contact': 'Contact Info',
    'footer.newsletter.title': 'Stay Updated',
    'footer.newsletter.subtitle': 'Get the latest insights and updates from our team.',
    'footer.newsletter.placeholder': 'Enter your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.copyright': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',

    // Common
    'common.optional': 'Optional',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.portfolio': 'Portfolio',
    'nav.services': 'Services',
    'nav.about': 'À Propos',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Commencer',

    // Hero Section
    'hero.title.we': 'Nous Créons des',
    'hero.title.digital': 'Expériences',
    'hero.title.experiences': 'Numériques',
    'hero.subtitle': 'Transformez votre marque avec des solutions numériques de pointe qui captivent, convertissent et accélèrent la croissance.',
    'hero.cta.start': 'Démarrer Votre Projet',
    'hero.cta.view': 'Voir Notre Travail',

    // Portfolio Section
    'portfolio.title': 'Notre',
    'portfolio.title.highlight': 'Portfolio',
    'portfolio.subtitle': 'Découvrez comment nous avons aidé les entreprises à transformer leur présence numérique.',
    'portfolio.cta.viewCase': 'Voir l\'Étude de Cas',
    'portfolio.cta.discuss': 'Discuter de Votre Projet',
    'portfolio.modal.challenge': 'Défi',
    'portfolio.modal.solution': 'Solution',
    'portfolio.modal.results': 'Résultats',
    'portfolio.modal.technologies': 'Technologies Utilisées',
    'portfolio.modal.ready': 'Prêt à obtenir des résultats similaires?',
    'portfolio.modal.cta': 'Démarrer Votre Projet',

    // Services Section
    'services.title': 'Nos',
    'services.title.highlight': 'Services',
    'services.subtitle': 'Solutions numériques complètes adaptées aux besoins de votre entreprise.',
    'services.strategy.title': 'Stratégie et Conseil',
    'services.strategy.description': 'Planification stratégique et conseil pour aligner vos initiatives numériques.',
    'services.strategy.brand': 'Stratégie de Marque',
    'services.strategy.digital': 'Transformation Numérique',
    'services.strategy.ux': 'Stratégie UX/UI',
    'services.strategy.conversion': 'Optimisation de Conversion',
    'services.strategy.analytics': 'Analyses et Insights',
    'services.development.title': 'Développement et Design',
    'services.development.description': 'Solutions de développement et design personnalisées.',
    'services.development.web': 'Développement Web',
    'services.development.mobile': 'Applications Mobiles',
    'services.development.ecommerce': 'Solutions E-commerce',
    'services.development.custom': 'Logiciels Personnalisés',
    'services.development.api': 'Développement API',
    'services.marketing.title': 'Marketing Numérique',
    'services.marketing.description': 'Stratégies marketing basées sur les données.',
    'services.marketing.seo': 'Optimisation SEO',
    'services.marketing.ppc': 'Publicité PPC',
    'services.marketing.social': 'Marketing des Réseaux Sociaux',
    'services.marketing.content': 'Marketing de Contenu',
    'services.marketing.email': 'Email Marketing',
    'services.cta.discuss': 'Discuter de ce Service',
    'services.cta.learn': 'En Savoir Plus',
    'services.cta.transform': 'Prêt à transformer votre entreprise?',
    'services.cta.getStarted': 'Commencer Aujourd\'hui',

    // Testimonials Section
    'testimonials.title': 'Ce que nos',
    'testimonials.title.highlight': 'Clients',
    'testimonials.title.say': 'disent',
    'testimonials.subtitle': "Ne vous fiez pas seulement à notre parole. Voici ce que nos clients disent de notre collaboration.",
    'testimonials.watchVideo': 'Voir la vidéo',
    'testimonials.trustedAcross': 'De nombreux secteurs nous font confiance',
    'testimonials.quote1': "Travailler avec Premium Events Solution a été un tournant pour notre entreprise. Leur approche stratégique et leur exécution sans faille ont dépassé nos attentes.",
    'testimonials.quote2': "L'expertise de l'équipe en transformation digitale nous a permis de moderniser toute notre opération. Notre efficacité a augmenté de 200%.",
    'testimonials.quote3': "Premium Events Solution ne livre pas seulement des projets, ils créent des partenariats. Leur soutien continu a été inestimable pour notre croissance.",
    'testimonials.quote4': "L'application web qu'ils ont développée a révolutionné la façon dont nos clients interagissent avec nos services. L'engagement utilisateur est au plus haut.",
    'testimonials.quote5': "Leur solution pour la plateforme santé a transformé notre prise en charge des patients. Nous n'avons jamais été aussi satisfaits.",
    'testimonials.industry.technology': 'Technologie',
    'testimonials.industry.saas': 'SaaS',
    'testimonials.industry.retail': 'Commerce de détail',
    'testimonials.industry.financial': 'Services financiers',
    'testimonials.industry.healthcare': 'Santé',
    'testimonials.project1': 'Transformation Digitale',
    'testimonials.project2': 'Plateforme SaaS',
    'testimonials.project3': 'Refonte de Marque',
    'testimonials.project4': 'Application Mobile',
    'testimonials.project5': 'Plateforme Santé',
    'testimonials.metric.conversion': 'Taux de conversion',
    'testimonials.metric.revenue': 'Croissance du chiffre d’affaires',
    'testimonials.metric.engagement': 'Engagement utilisateur',
    'testimonials.metric.acquisition': 'Acquisition utilisateur',
    'testimonials.metric.adoption': 'Adoption de fonctionnalités',
    'testimonials.metric.market': 'Part de marché',
    'testimonials.metric.recognition': 'Reconnaissance de la marque',
    'testimonials.metric.sales': 'Ventes en ligne',
    'testimonials.metric.satisfaction': 'Satisfaction client',
    'testimonials.metric.downloads': 'Téléchargements de l’application',
    'testimonials.metric.retention': 'Rétention utilisateur',
    'testimonials.metric.transactions': 'Transactions quotidiennes',
    'testimonials.metric.patientSat': 'Satisfaction patient',
    'testimonials.metric.efficiency': 'Efficacité opérationnelle',
    'testimonials.metric.platformAdoption': 'Adoption de la plateforme',

    // About Section
    'about.title': 'À propos',
    'about.title.highlight': 'Premium Events Solution',
    'about.subtitle': "Nous sommes une équipe de passionnés du digital dédiée à la transformation des entreprises grâce à la technologie et à la créativité.",
    'about.stats.clients': 'Clients satisfaits',
    'about.stats.projects': 'Projets réalisés',
    'about.stats.awards': 'Récompenses',
    'about.stats.experience': "Années d'expérience", 
    'about.mission.title': 'Notre mission',
    'about.mission.text': "Donner aux entreprises les moyens de réussir grâce à des solutions digitales qui anticipent les défis de demain.",
    'about.team.title': 'Notre équipe',
    'about.team.subtitle': 'Les esprits créatifs derrière notre succès',
    'about.team.viewProfile': 'Voir le profil',
    'about.team.joined': 'A rejoint',
    'about.team.aboutPerson': 'À propos',
    'about.team.expertise': 'Expertise',
    'about.team.achievements': 'Réalisations clés',
    'about.team.interests': 'Centres d’intérêt',
    'about.team.workingStyle': 'Style de travail',
    'about.culture.title': 'Notre culture & valeurs',
    'about.culture.innovation.title': 'Innovation avant tout',
    'about.culture.innovation.description': 'Nous adoptons les technologies de pointe et les solutions créatives.',
    'about.culture.innovation.example1': 'Sessions innovation hebdomadaires',
    'about.culture.innovation.example2': 'Temps de projet expérimental',
    'about.culture.innovation.example3': 'Initiatives de recherche technologique',
    'about.culture.excellence.title': 'L’excellence en tout',
    'about.culture.excellence.description': 'Nous maintenons les plus hauts standards dans notre travail.',
    'about.culture.excellence.example1': 'Assurance qualité rigoureuse',
    'about.culture.excellence.example2': 'Processus d’amélioration continue',
    'about.culture.excellence.example3': 'Meilleures pratiques du secteur',
    'about.culture.partnership.title': 'Véritable partenariat',
    'about.culture.partnership.description': 'Nous travaillons comme une extension de votre équipe.',
    'about.culture.partnership.example1': 'Sessions de planification collaborative',
    'about.culture.partnership.example2': 'Communication transparente',
    'about.culture.partnership.example3': 'Relation à long terme',
    'about.culture.balance.title': 'Équilibre vie pro/perso',
    'about.culture.balance.description': 'Nous croyons que le bien-être de l’équipe est la clé du succès.',
    'about.culture.balance.example1': 'Horaires flexibles',
    'about.culture.balance.example2': 'Programmes bien-être',
    'about.culture.balance.example3': 'Activités de team building',
    'about.culture.inPractice': 'En pratique',
    'about.life.title': 'La vie chez Premium Events Solution',
    'about.life.subtitle': 'Plus qu’un travail, une communauté',
    'about.life.coffee.title': 'Café & créativité',
    'about.life.coffee.description': 'Nos meilleures idées naissent autour d’un café',
    'about.life.innovation.title': 'Labs d’innovation',
    'about.life.innovation.description': 'Temps dédié aux projets expérimentaux',
    'about.life.balance.title': 'Équilibre vie pro/perso',
    'about.life.balance.description': 'Horaires flexibles et télétravail',

    // Team member details
    'about.team.alex.role': 'Directeur créatif & fondateur',
    'about.team.alex.bio': 'Leader visionnaire avec plus de 10 ans dans le design digital et la stratégie.',
    'about.team.alex.fullBio': "Alex a fondé Premium Events Solution pour allier excellence créative et innovation technique. Il a mené des projets de transformation pour des grands groupes et des startups.",
    'about.team.alex.expertise1': 'Direction créative',
    'about.team.alex.expertise2': 'Stratégie de marque',
    'about.team.alex.expertise3': 'Design systems',
    'about.team.alex.expertise4': 'Leadership d’équipe',
    'about.team.alex.achievement1': 'Plus de 50 transformations de marque réussies',
    'about.team.alex.achievement2': 'Lauréat Webby Award 2023',
    'about.team.alex.achievement3': 'Mis en avant dans Design Week Magazine',
    'about.team.alex.achievement4': 'Conférencier dans 15+ événements',
    'about.team.alex.interest1': 'Photographie',
    'about.team.alex.interest2': 'VTT',
    'about.team.alex.interest3': 'Torréfaction de café',
    'about.team.alex.interest4': 'Voyages',
    'about.team.alex.quote': "Le bon design ne se limite pas à l’apparence, mais à l’émotion qu’il suscite.",
    'about.team.alex.workingStyle': 'Collaboratif et impliqué, il prône la créativité par la communication ouverte.',

    'about.team.sarah.role': 'Lead développeuse',
    'about.team.sarah.bio': 'Développeuse full-stack passionnée par les solutions évolutives.',
    'about.team.sarah.fullBio': "Sarah apporte excellence technique et résolution innovante. Experte en technologies web modernes, elle crée des solutions évolutives et maintenables.",
    'about.team.sarah.expertise1': 'Développement full-stack',
    'about.team.sarah.expertise2': 'Architecture cloud',
    'about.team.sarah.expertise3': 'DevOps',
    'about.team.sarah.expertise4': 'Optimisation des performances',
    'about.team.sarah.achievement1': 'Plus de 30 applications web évolutives',
    'about.team.sarah.achievement2': 'Certifiée AWS Solutions Architect',
    'about.team.sarah.achievement3': 'Contributrice open source',
    'about.team.sarah.achievement4': 'Conférencière tech',
    'about.team.sarah.interest1': 'Escalade',
    'about.team.sarah.interest2': 'Cuisine',
    'about.team.sarah.interest3': 'Jeux de société',
    'about.team.sarah.interest4': 'Podcasts',
    'about.team.sarah.quote': 'Le code est une poésie pour les machines, mais lue par les humains.',
    'about.team.sarah.workingStyle': 'Rigoureuse et méthodique, elle privilégie le code propre et le mentorat.',

    'about.team.david.role': 'Stratège marketing digital',
    'about.team.david.bio': 'Marketeur data-driven, expert en growth hacking et analytics.',
    'about.team.david.fullBio': "David allie analyse et créativité pour générer de la croissance. Son approche data-driven a permis à de nombreuses entreprises d’atteindre des résultats exceptionnels.",
    'about.team.david.expertise1': 'Growth marketing',
    'about.team.david.expertise2': 'Analytics & data',
    'about.team.david.expertise3': 'SEO/SEM',
    'about.team.david.expertise4': 'Optimisation de conversion',
    'about.team.david.achievement1': 'ROI client augmenté de 300% en moyenne',
    'about.team.david.achievement2': 'Expert certifié Google Ads',
    'about.team.david.achievement3': 'Formateur certifié HubSpot',
    'about.team.david.achievement4': 'Spécialiste marketing automation',
    'about.team.david.interest1': 'Data science',
    'about.team.david.interest2': 'Basket',
    'about.team.david.interest3': 'Lecture',
    'about.team.david.interest4': 'Voyages',
    'about.team.david.quote': "En marketing, la data raconte l’histoire, la créativité la fait vivre.",
    'about.team.david.workingStyle': 'Analytique et orienté résultats, il teste tout et décide sur la base de données.',

    'about.team.maya.role': 'Designer UX/UI',
    'about.team.maya.bio': 'Designer centrée utilisateur, spécialisée dans la création d’expériences numériques intuitives.',
    'about.team.maya.fullBio': 'Maya est passionnée par la création d’expériences numériques à la fois belles, intuitives et accessibles. Son approche centrée utilisateur garantit que chaque interface conçue répond réellement aux besoins des utilisateurs.',
    'about.team.maya.expertise1': 'Conception d’expérience utilisateur',
    'about.team.maya.expertise2': 'Design d’interface',
    'about.team.maya.expertise3': 'Design systems',
    'about.team.maya.expertise4': 'Recherche utilisateur',
    'about.team.maya.achievement1': 'A conçu plus de 40 interfaces primées',
    'about.team.maya.achievement2': 'Certification UX de Nielsen Norman',
    'about.team.maya.achievement3': 'Formatrice et défenseure de l’accessibilité',
    'about.team.maya.achievement4': 'Animatrice d’ateliers design thinking',
    'about.team.maya.interest1': 'Peinture',
    'about.team.maya.interest2': 'Yoga',
    'about.team.maya.interest3': 'Vie durable',
    'about.team.maya.interest4': 'Musées',
    'about.team.maya.quote': 'Le design n’est pas seulement ce à quoi il ressemble et ce qu’il ressent. Le design, c’est comment cela fonctionne.',
    'about.team.maya.workingStyle': 'Empathique et centrée utilisateur, elle mène des recherches approfondies et itère selon les retours des utilisateurs.',
    
    // Social Proof Section
    'socialProof.title': 'Ils nous font confiance',
    'socialProof.title.highlight': 'Leaders du secteur',
    'socialProof.subtitle': 'Rejoignez les entreprises qui nous confient leur transformation digitale.',
    'socialProof.industry.technology': 'Technologie',
    'socialProof.industry.saas': 'SaaS',
    'socialProof.industry.retail': 'Commerce de détail',
    'socialProof.industry.fintech': 'FinTech',
    'socialProof.industry.healthcare': 'Santé',
    'socialProof.industry.education': 'Éducation',
    'socialProof.industry.energy': 'Énergie',
    'socialProof.industry.food': 'Agroalimentaire',
    'socialProof.awards.title': 'Récompenses',
    'socialProof.awards.subtitle': 'Notre travail reconnu par le secteur',
    'socialProof.awards.webby.title': 'Webby Awards',
    'socialProof.awards.webby.category': 'Meilleur design web',
    'socialProof.awards.webby.description': 'Récompensé pour l’expérience utilisateur',
    'socialProof.awards.css.title': 'CSS Design Awards',
    'socialProof.awards.css.category': 'Site du jour',
    'socialProof.awards.css.description': 'Mise en avant pour la créativité CSS',
    'socialProof.awards.awwwards.title': 'Awwwards',
    'socialProof.awards.awwwards.category': 'Prix développeur',
    'socialProof.awards.awwwards.description': 'Excellence technique et innovation',
    'socialProof.awards.fwa.title': 'FWA',
    'socialProof.awards.fwa.category': 'Site du mois',
    'socialProof.awards.fwa.description': 'Développement web de pointe',
    'socialProof.numbers.title': 'Nos chiffres clés',
    'socialProof.numbers.subtitle': 'Notre bilan parle de lui-même',
    'socialProof.stats.satisfaction.label': 'Satisfaction client',
    'socialProof.stats.satisfaction.description': 'Note moyenne de satisfaction',
    'socialProof.stats.projects.label': 'Projets réalisés',
    'socialProof.stats.projects.description': 'Projets livrés avec succès',
    'socialProof.stats.clients.label': 'Clients satisfaits',
    'socialProof.stats.clients.description': 'Entreprises accompagnées',
    'socialProof.stats.experience.label': "Années d'expérience",
    'socialProof.stats.experience.description': 'Expérience cumulée de l’équipe',
    'socialProof.partners.title': 'Certifications & Partenariats',
    'socialProof.partners.subtitle': 'Nous respectons les standards du secteur',
    'socialProof.certifications.google': 'Partenaire Google',
    'socialProof.certifications.aws': 'Certifié AWS',
    'socialProof.certifications.hubspot': 'Partenaire HubSpot',
    'socialProof.certifications.shopify': 'Expert Shopify',
    'socialProof.certifications.meta': 'Partenaire Meta',
    'socialProof.certifications.microsoft': 'Partenaire Microsoft',
    'socialProof.cta.text': 'Prêt à rejoindre nos success stories ?',
    'socialProof.cta.button': 'Démarrer votre projet',
    
    // Section Contact
    'contact.title': 'Contact',
    'contact.title.highlight': 'Nous joindre',
    'contact.subtitle': 'Prêt à transformer votre présence digitale ? Discutons de votre projet et voyons comment nous pouvons vous aider à atteindre vos objectifs.',
    'contact.getInTouch': 'Prendre contact',
    'contact.description': 'Nous serions ravis d’en savoir plus sur votre projet et d’échanger sur la façon dont nous pouvons concrétiser votre vision.',
    'contact.email.description': 'Envoyez-nous un email à tout moment',
    'contact.phone.description': 'Appelez-nous pendant les heures ouvrables',
    'contact.location.description': 'Venez nous rendre visite',
    'contact.whatToExpected': 'À quoi s’attendre',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.subtitle': 'Remplissez le formulaire ci-dessous et nous vous répondrons sous 24h.',
    'contact.form.name': 'Nom complet',
    'contact.form.email': 'Adresse email',
    'contact.form.company': 'Entreprise',
    'contact.form.message': 'Message',
    'contact.form.send': 'Envoyer le message',
    'contact.form.sending': 'Envoi en cours...',
    'contact.form.success': 'Message envoyé !',
    'contact.form.successText': 'Merci pour votre message. Nous vous répondrons sous 24h.',
    'contact.form.privacy': 'Nous respectons votre vie privée et ne partagerons jamais vos informations.', 

    // Footer
    'footer.description': 'Nous créons des expériences digitales qui captivent, convertissent et accélèrent la croissance.',
    'footer.quickLinks': 'Liens rapides',
    'footer.services': 'Services',
    'footer.services.brand': 'Stratégie de marque',
    'footer.services.web': 'Développement web',
    'footer.services.marketing': 'Marketing digital',
    'footer.services.mobile': 'Applications mobiles',
    'footer.services.ecommerce': 'E-commerce',
    'footer.services.seo': 'Optimisation SEO',
    'footer.contact': 'Contact',
    'footer.newsletter.title': 'Restez informé',
    'footer.newsletter.subtitle': 'Recevez nos actualités et conseils.',
    'footer.newsletter.placeholder': 'Votre email',
    'footer.newsletter.subscribe': 'S’abonner',
    'footer.copyright': 'Tous droits réservés.',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d’utilisation',
    'footer.cookies': 'Politique de cookies',

    // Common
    'common.optional': 'Optionnel',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};